version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      aksel:
        applies-to: version-updates
        patterns:
          - "@navikt/aksel*"
          - "@navikt/ds*"
      react-router:
        applies-to: version-updates
        patterns:
          - "@react-router*"
          - "react-router*"
