allowBuilds:
  esbuild: true
  lefthook: true
  msw: true
  protobufjs: false
minimumReleaseAgeExclude:
  - '@react-router/dev@8.1.0'
  - '@react-router/express@8.1.0'
  - '@react-router/node@8.1.0'
  - '@react-router/serve@8.1.0'
  - react-router@8.1.0
